version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"